// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.5c/896140 Production Release
//  HLS Date:       Sun Sep  6 22:45:38 PDT 2020
// 
//  Generated by:   r0678912@amazone.esat.kuleuven.be
//  Generated date: Tue Jul 13 10:58:00 2021
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    tiling_unit_5_O_addr_type_L2_run
// ------------------------------------------------------------------


module tiling_unit_5_O_addr_type_L2_run (
  loops_bound_rsc_dat, loops_relevancy_rsc_dat, tile_size_in_rsc_dat, tile_size_out_rsc_z,
      instr_bound_rsc_z, instr_tile_rsc_z, ccs_ccore_start_rsc_dat, ccs_ccore_clk,
      ccs_ccore_srst, ccs_ccore_en
);
  input [44:0] loops_bound_rsc_dat;
  input [4:0] loops_relevancy_rsc_dat;
  input [8:0] tile_size_in_rsc_dat;
  output [8:0] tile_size_out_rsc_z;
  output [44:0] instr_bound_rsc_z;
  output [44:0] instr_tile_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_ccore_clk;
  input ccs_ccore_srst;
  input ccs_ccore_en;


  // Interconnect Declarations
  wire [44:0] loops_bound_rsci_idat;
  wire [4:0] loops_relevancy_rsci_idat;
  wire [8:0] tile_size_in_rsci_idat;
  wire ccs_ccore_start_rsci_idat;
  reg [8:0] instr_bound_rsci_d_44_36;
  reg [8:0] instr_bound_rsci_d_35_27;
  reg [8:0] instr_bound_rsci_d_26_18;
  reg [8:0] instr_bound_rsci_d_17_9;
  reg [8:0] instr_bound_rsci_d_8_0;
  reg [3:0] instr_tile_rsci_d_8_5;
  reg [4:0] instr_tile_rsci_d_4_0;
  reg [3:0] instr_tile_rsci_d_35_32;
  reg [4:0] instr_tile_rsci_d_31_27;
  reg [3:0] instr_tile_rsci_d_26_23;
  reg [4:0] instr_tile_rsci_d_22_18;
  reg [3:0] instr_tile_rsci_d_17_14;
  reg [4:0] instr_tile_rsci_d_13_9;
  reg [3:0] reg_tile_size_out_rsci_d_8_5_cse;
  reg [4:0] reg_tile_size_out_rsci_d_4_0_cse;
  wire [4:0] instr_tile_rsci_d_4_0_mx0;
  wire [3:0] instr_tile_rsci_d_35_32_mx0;
  wire [4:0] instr_tile_rsci_d_31_27_mx0;
  wire [3:0] tile_size_int_lpi_1_dfm_8_5_1;
  wire [3:0] instr_tile_rsci_d_26_23_mx0;
  wire [4:0] instr_tile_rsci_d_22_18_mx0;
  wire [3:0] instr_tile_rsci_d_17_14_mx0;
  wire [4:0] instr_tile_rsci_d_13_9_mx0;
  wire [8:0] tile_size_int_sva_6;
  wire [13:0] nl_tile_size_int_sva_6;
  wire [8:0] tile_size_int_sva_7;
  wire [17:0] nl_tile_size_int_sva_7;
  wire [8:0] tile_size_int_sva_8;
  wire [17:0] nl_tile_size_int_sva_8;
  wire [8:0] tile_size_int_sva_9;
  wire [17:0] nl_tile_size_int_sva_9;
  wire [8:0] tile_size_int_sva_10;
  wire [17:0] nl_tile_size_int_sva_10;
  wire tile_size_and_cse;


  // Interconnect Declarations for Component Instantiations 
  wire [44:0] nl_instr_bound_rsci_d;
  assign nl_instr_bound_rsci_d = {instr_bound_rsci_d_44_36 , instr_bound_rsci_d_35_27
      , instr_bound_rsci_d_26_18 , instr_bound_rsci_d_17_9 , instr_bound_rsci_d_8_0};
  wire [44:0] nl_instr_tile_rsci_d;
  assign nl_instr_tile_rsci_d = {reg_tile_size_out_rsci_d_8_5_cse , reg_tile_size_out_rsci_d_4_0_cse
      , instr_tile_rsci_d_35_32 , instr_tile_rsci_d_31_27 , instr_tile_rsci_d_26_23
      , instr_tile_rsci_d_22_18 , instr_tile_rsci_d_17_14 , instr_tile_rsci_d_13_9
      , instr_tile_rsci_d_8_5 , instr_tile_rsci_d_4_0};
  wire [8:0] nl_tile_size_out_rsci_d;
  assign nl_tile_size_out_rsci_d = {reg_tile_size_out_rsci_d_8_5_cse , reg_tile_size_out_rsci_d_4_0_cse};
  ccs_in_v1 #(.rscid(32'sd6),
  .width(32'sd45)) loops_bound_rsci (
      .dat(loops_bound_rsc_dat),
      .idat(loops_bound_rsci_idat)
    );
  ccs_in_v1 #(.rscid(32'sd7),
  .width(32'sd5)) loops_relevancy_rsci (
      .dat(loops_relevancy_rsc_dat),
      .idat(loops_relevancy_rsci_idat)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd9),
  .width(32'sd45)) instr_bound_rsci (
      .d(nl_instr_bound_rsci_d[44:0]),
      .z(instr_bound_rsc_z)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd10),
  .width(32'sd45)) instr_tile_rsci (
      .d(nl_instr_tile_rsci_d[44:0]),
      .z(instr_tile_rsc_z)
    );
  ccs_in_v1 #(.rscid(32'sd128),
  .width(32'sd9)) tile_size_in_rsci (
      .dat(tile_size_in_rsc_dat),
      .idat(tile_size_in_rsci_idat)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd129),
  .width(32'sd9)) tile_size_out_rsci (
      .d(nl_tile_size_out_rsci_d[8:0]),
      .z(tile_size_out_rsc_z)
    );
  ccs_in_v1 #(.rscid(32'sd136),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  assign tile_size_and_cse = ccs_ccore_en & ccs_ccore_start_rsci_idat;
  assign instr_tile_rsci_d_4_0_mx0 = MUX_v_5_2_2((tile_size_in_rsci_idat[4:0]), (tile_size_int_sva_6[4:0]),
      loops_relevancy_rsci_idat[0]);
  assign instr_tile_rsci_d_35_32_mx0 = MUX_v_4_2_2(instr_tile_rsci_d_26_23_mx0, (tile_size_int_sva_9[8:5]),
      loops_relevancy_rsci_idat[3]);
  assign instr_tile_rsci_d_31_27_mx0 = MUX_v_5_2_2(instr_tile_rsci_d_22_18_mx0, (tile_size_int_sva_9[4:0]),
      loops_relevancy_rsci_idat[3]);
  assign tile_size_int_lpi_1_dfm_8_5_1 = MUX_v_4_2_2(4'b0000, (tile_size_int_sva_6[8:5]),
      (loops_relevancy_rsci_idat[0]));
  assign instr_tile_rsci_d_26_23_mx0 = MUX_v_4_2_2(instr_tile_rsci_d_17_14_mx0, (tile_size_int_sva_8[8:5]),
      loops_relevancy_rsci_idat[2]);
  assign instr_tile_rsci_d_22_18_mx0 = MUX_v_5_2_2(instr_tile_rsci_d_13_9_mx0, (tile_size_int_sva_8[4:0]),
      loops_relevancy_rsci_idat[2]);
  assign instr_tile_rsci_d_17_14_mx0 = MUX_v_4_2_2(tile_size_int_lpi_1_dfm_8_5_1,
      (tile_size_int_sva_7[8:5]), loops_relevancy_rsci_idat[1]);
  assign instr_tile_rsci_d_13_9_mx0 = MUX_v_5_2_2(instr_tile_rsci_d_4_0_mx0, (tile_size_int_sva_7[4:0]),
      loops_relevancy_rsci_idat[1]);
  assign nl_tile_size_int_sva_6 = (tile_size_in_rsci_idat[4:0]) * (loops_bound_rsci_idat[8:0]);
  assign tile_size_int_sva_6 = nl_tile_size_int_sva_6[8:0];
  assign nl_tile_size_int_sva_7 = ({tile_size_int_lpi_1_dfm_8_5_1 , instr_tile_rsci_d_4_0_mx0})
      * (loops_bound_rsci_idat[17:9]);
  assign tile_size_int_sva_7 = nl_tile_size_int_sva_7[8:0];
  assign nl_tile_size_int_sva_8 = ({instr_tile_rsci_d_17_14_mx0 , instr_tile_rsci_d_13_9_mx0})
      * (loops_bound_rsci_idat[26:18]);
  assign tile_size_int_sva_8 = nl_tile_size_int_sva_8[8:0];
  assign nl_tile_size_int_sva_9 = ({instr_tile_rsci_d_26_23_mx0 , instr_tile_rsci_d_22_18_mx0})
      * (loops_bound_rsci_idat[35:27]);
  assign tile_size_int_sva_9 = nl_tile_size_int_sva_9[8:0];
  assign nl_tile_size_int_sva_10 = ({instr_tile_rsci_d_35_32_mx0 , instr_tile_rsci_d_31_27_mx0})
      * (loops_bound_rsci_idat[44:36]);
  assign tile_size_int_sva_10 = nl_tile_size_int_sva_10[8:0];
  always @(posedge ccs_ccore_clk) begin
    if ( ccs_ccore_srst ) begin
      reg_tile_size_out_rsci_d_8_5_cse <= 4'b0000;
      reg_tile_size_out_rsci_d_4_0_cse <= 5'b00000;
      instr_tile_rsci_d_8_5 <= 4'b0000;
    end
    else if ( tile_size_and_cse ) begin
      reg_tile_size_out_rsci_d_8_5_cse <= MUX_v_4_2_2(instr_tile_rsci_d_35_32_mx0,
          (tile_size_int_sva_10[8:5]), loops_relevancy_rsci_idat[4]);
      reg_tile_size_out_rsci_d_4_0_cse <= MUX_v_5_2_2(instr_tile_rsci_d_31_27_mx0,
          (tile_size_int_sva_10[4:0]), loops_relevancy_rsci_idat[4]);
      instr_tile_rsci_d_8_5 <= tile_size_int_lpi_1_dfm_8_5_1;
    end
  end
  always @(posedge ccs_ccore_clk) begin
    if ( ccs_ccore_srst ) begin
      instr_bound_rsci_d_44_36 <= 9'b000000000;
      instr_bound_rsci_d_8_0 <= 9'b000000000;
      instr_bound_rsci_d_35_27 <= 9'b000000000;
      instr_bound_rsci_d_17_9 <= 9'b000000000;
      instr_bound_rsci_d_26_18 <= 9'b000000000;
      instr_tile_rsci_d_4_0 <= 5'b00000;
      instr_tile_rsci_d_35_32 <= 4'b0000;
      instr_tile_rsci_d_31_27 <= 5'b00000;
      instr_tile_rsci_d_26_23 <= 4'b0000;
      instr_tile_rsci_d_22_18 <= 5'b00000;
      instr_tile_rsci_d_17_14 <= 4'b0000;
      instr_tile_rsci_d_13_9 <= 5'b00000;
    end
    else if ( ccs_ccore_en ) begin
      instr_bound_rsci_d_44_36 <= MUX_v_9_2_2((loops_bound_rsci_idat[44:36]), 9'b000000001,
          loops_relevancy_rsci_idat[4]);
      instr_bound_rsci_d_8_0 <= MUX_v_9_2_2((loops_bound_rsci_idat[8:0]), 9'b000000001,
          loops_relevancy_rsci_idat[0]);
      instr_bound_rsci_d_35_27 <= MUX_v_9_2_2((loops_bound_rsci_idat[35:27]), 9'b000000001,
          loops_relevancy_rsci_idat[3]);
      instr_bound_rsci_d_17_9 <= MUX_v_9_2_2((loops_bound_rsci_idat[17:9]), 9'b000000001,
          loops_relevancy_rsci_idat[1]);
      instr_bound_rsci_d_26_18 <= MUX_v_9_2_2((loops_bound_rsci_idat[26:18]), 9'b000000001,
          loops_relevancy_rsci_idat[2]);
      instr_tile_rsci_d_4_0 <= instr_tile_rsci_d_4_0_mx0;
      instr_tile_rsci_d_35_32 <= instr_tile_rsci_d_35_32_mx0;
      instr_tile_rsci_d_31_27 <= instr_tile_rsci_d_31_27_mx0;
      instr_tile_rsci_d_26_23 <= instr_tile_rsci_d_26_23_mx0;
      instr_tile_rsci_d_22_18 <= instr_tile_rsci_d_22_18_mx0;
      instr_tile_rsci_d_17_14 <= instr_tile_rsci_d_17_14_mx0;
      instr_tile_rsci_d_13_9 <= instr_tile_rsci_d_13_9_mx0;
    end
  end

  function automatic [3:0] MUX_v_4_2_2;
    input [3:0] input_0;
    input [3:0] input_1;
    input [0:0] sel;
    reg [3:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_4_2_2 = result;
  end
  endfunction


  function automatic [4:0] MUX_v_5_2_2;
    input [4:0] input_0;
    input [4:0] input_1;
    input [0:0] sel;
    reg [4:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_5_2_2 = result;
  end
  endfunction


  function automatic [8:0] MUX_v_9_2_2;
    input [8:0] input_0;
    input [8:0] input_1;
    input [0:0] sel;
    reg [8:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_9_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    tiling_unit_5_O_addr_type_L2
// ------------------------------------------------------------------


module tiling_unit_5_O_addr_type_L2 (
  loops_bound_rsc_dat, loops_relevancy_rsc_dat, tile_size_in_rsc_dat, tile_size_out_rsc_z,
      instr_bound_rsc_z, instr_tile_rsc_z, ccs_ccore_start_rsc_dat, ccs_ccore_clk,
      ccs_ccore_srst, ccs_ccore_en
);
  input [44:0] loops_bound_rsc_dat;
  input [4:0] loops_relevancy_rsc_dat;
  input [8:0] tile_size_in_rsc_dat;
  output [8:0] tile_size_out_rsc_z;
  output [44:0] instr_bound_rsc_z;
  output [44:0] instr_tile_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_ccore_clk;
  input ccs_ccore_srst;
  input ccs_ccore_en;



  // Interconnect Declarations for Component Instantiations 
  tiling_unit_5_O_addr_type_L2_run tiling_unit_5_O_addr_type_L2_run_inst (
      .loops_bound_rsc_dat(loops_bound_rsc_dat),
      .loops_relevancy_rsc_dat(loops_relevancy_rsc_dat),
      .tile_size_in_rsc_dat(tile_size_in_rsc_dat),
      .tile_size_out_rsc_z(tile_size_out_rsc_z),
      .instr_bound_rsc_z(instr_bound_rsc_z),
      .instr_tile_rsc_z(instr_tile_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_ccore_clk(ccs_ccore_clk),
      .ccs_ccore_srst(ccs_ccore_srst),
      .ccs_ccore_en(ccs_ccore_en)
    );
endmodule



