
## SLEC script generated by PowerPro 10.3c_2
# from directory: /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF

set required_slec_version 10.3
if { [llength [info commands check_minimum_version]] } {
    check_minimum_version $required_slec_version
} else {
    issue_warning "This version of SLEC ([get_version]) is older than the certified requirement ($required_slec_version). Some features may not be compatible."
}
 

#  Setting verification_mode
set_verification_mode -powerpro 

#  Globals transferred from the parent session

# Sets the number of characters to display per line.
set_global message_wrap_at 10000

# Disabled type checking for transactor port
set_global _tdb_check_only_width_for_transactor_port 1

# Design build globals 
set_global maximum_iter_count 1024
set_global maximum_recurse_count 100
set_global set_zero_replicate_to_null 1

# Enable inout support
set_global opt_isolate_inout_ports 1

# Enable multi driver support
set_global _opt_isolate_multi_drivers 1

# Enable Mixed Language Support
set_global enable_mixed_language_support 1

# Enable SV Mixed Language Support
set_global _allow_sv_in_mixed_language 1

set_global _new_fe_enable 1

set_global _enable_sv_assertion_synthesis 0

set_global error_for_missing_modules 1
 

#  Reading libraries.
read_library /esat/micas-data/software/Mentor/catapult_10.5c/pkgs/siflibs/nangate/nangate45nm_\
nldm.lib 

## Writing define_memory_operation commands for creating power-opts.
 

## Build Design Specification for Spec Design
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library calypto_lib -vhdl /esat/micas-data/software/Mentor/catapult_10.5c/pkgs/c\
ds_ppro/rls/platform/common/powerpro/powerpro_cg_package.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library calypto_lib -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/\
Catapult/SIF/./top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_t\
ype_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5\
_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_part\
ial_000024_enLogic.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000001.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000003.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000007.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000009.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_1.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_2.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_3.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_4.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_5.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -spec -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
000.vhdl 
popd 
link_design -top top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_type_L1_5_288_8_8\
_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_8640_8_8_O_addr\
_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_partial_000000 -spec 
build_db -spec 

#  Processing existing asynchronous reset
process_async_resets -spec 

## Build Design Specification for Impl Design
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library calypto_lib -vhdl /esat/micas-data/software/Mentor/catapult_10.5c/pkgs/c\
ds_ppro/rls/platform/common/powerpro/powerpro_cg_package.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library calypto_lib -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/\
Catapult/SIF/./top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_t\
ype_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5\
_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_part\
ial_000024_enLogic.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000001.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000003.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000007.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library mgc_hls -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Cata\
pult/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr\
_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2\
_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa\
000009.vhd 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_1.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_2.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_3.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_4.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
005_5.vhdl 
popd 
pushd /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapult/SIF 

  
read_design -impl -library work -vhdl /users/students/r0678912/Downloads/zigzag/hls_impl/PE/Catapul\
t/SIF/./power_top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_ty\
pe_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_\
8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_pa000\
000.vhdl 
popd 
link_design -top top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_type_L1_5_288_8_8\
_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_8640_8_8_O_addr\
_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_partial_000000 -impl 
build_db -impl 

#  Processing existing asynchronous reset
process_async_resets -impl 

#  To Black-box tech cells 
blackbox_tech_cells 

#  Handling Auto Infer Clocks.

#  Handling Auto Infer internal signals
set spec_bbox_out_port_list {}
set impl_bbox_out_port_list {}
 

## Transactors for qualified flop-mappings
 

#  Generate independent clocks

# Clock Root Command
set_clock_root -clock _Ideal_Clk_ -enable powerpro_independent_clock_0 {spec.clk} {impl.clk} 

#Enabling/Disabling Valid Maps on Hard Operators
set enable_valid_on_hard_op 0
 

#  Qualified flop-mappings
ksource -key 4223421293 self_verify_script_maps.tcl 

#  Name-based flop-mapping
create_namemap_rule -default -ignore_latches 
set_global cut_at_mapped_flops 1 

#  Setting verify mode
verify -mode full_proof 

## In case problems get aborted due to run-time,issue PowerPro directives to be used in a later run
dump_powerpro_hard_maps 
dump_powerpro_hard_maps_old 

#  Setting verification status
assert_maps_proven [print_status] 
