# build_design script generated by PowerPro
set_verification_mode -powerpro

# Global For Mixed Language Support.
set_global enable_mixed_language_support 1

# Turning off global For SV Assertion synthesis Support.
set_global _enable_sv_assertion_synthesis 0

# Global For SV Language Support.
set_global _allow_sv_in_mixed_language 1

# Global For invoking new FE for slec.
set_global _slec_new_fe_enable 1
pushd [file dirname [info script]]
read_design -f rtl_mod_rel_verilog.f -verilog
cpt::mixed_lang_to_cpt top_5_32_1_1_O_addr_type_L1_32_1_1_I_addr_type_L1_32_1_1_W_addr_type_L1_5_288_8_8_O_addr_type_L2_312_8_8_I_addr_type_L2_1728_8_8_W_addr_type_L2_5_8640_8_8_O_addr_type_L3_8640_8_8_I_addr_type_L3_55296_8_8_W_addr_type_L3_O_partial_000000 -bb_list { } -cpt_lib work  -only_elaborate_no_cpt 1 
popd
