#!/bin/csh
# path to Catapult MGC_HOME dir
setenv CCS_HOME $MGC_HOME
clear

set rootdir = `dirname $0`
set abs_rootdir = `cd $rootdir && pwd`
cd abs_rootdir

g++ -g -O0 -std=c++11 -I $CCS_HOME/shared/include testbench.cpp -o testbench && ./testbench
