// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.5c/896140 Production Release
//  HLS Date:       Sun Sep  6 22:45:38 PDT 2020
// 
//  Generated by:   r0678912@amazone.esat.kuleuven.be
//  Generated date: Tue Jul 13 10:57:58 2021
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    tiling_unit_5_O_addr_type_L3_run
// ------------------------------------------------------------------


module tiling_unit_5_O_addr_type_L3_run (
  loops_bound_rsc_dat, loops_relevancy_rsc_dat, tile_size_in_rsc_dat, tile_size_out_rsc_z,
      instr_bound_rsc_z, instr_tile_rsc_z, ccs_ccore_start_rsc_dat, ccs_ccore_clk,
      ccs_ccore_srst, ccs_ccore_en
);
  input [69:0] loops_bound_rsc_dat;
  input [4:0] loops_relevancy_rsc_dat;
  input [13:0] tile_size_in_rsc_dat;
  output [13:0] tile_size_out_rsc_z;
  output [69:0] instr_bound_rsc_z;
  output [69:0] instr_tile_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_ccore_clk;
  input ccs_ccore_srst;
  input ccs_ccore_en;


  // Interconnect Declarations
  wire [69:0] loops_bound_rsci_idat;
  wire [4:0] loops_relevancy_rsci_idat;
  wire [13:0] tile_size_in_rsci_idat;
  wire ccs_ccore_start_rsci_idat;
  reg [13:0] instr_bound_rsci_d_69_56;
  reg [13:0] instr_bound_rsci_d_55_42;
  reg [13:0] instr_bound_rsci_d_41_28;
  reg [13:0] instr_bound_rsci_d_27_14;
  reg [13:0] instr_bound_rsci_d_13_0;
  reg [4:0] instr_tile_rsci_d_13_9;
  reg [8:0] instr_tile_rsci_d_8_0;
  reg [4:0] instr_tile_rsci_d_55_51;
  reg [8:0] instr_tile_rsci_d_50_42;
  reg [4:0] instr_tile_rsci_d_41_37;
  reg [8:0] instr_tile_rsci_d_36_28;
  reg [4:0] instr_tile_rsci_d_27_23;
  reg [8:0] instr_tile_rsci_d_22_14;
  reg [4:0] reg_tile_size_out_rsci_d_13_9_cse;
  reg [8:0] reg_tile_size_out_rsci_d_8_0_cse;
  wire [8:0] instr_tile_rsci_d_8_0_mx0;
  wire [4:0] instr_tile_rsci_d_55_51_mx0;
  wire [8:0] instr_tile_rsci_d_50_42_mx0;
  wire [4:0] tile_size_int_lpi_1_dfm_13_9_1;
  wire [4:0] instr_tile_rsci_d_41_37_mx0;
  wire [8:0] instr_tile_rsci_d_36_28_mx0;
  wire [4:0] instr_tile_rsci_d_27_23_mx0;
  wire [8:0] instr_tile_rsci_d_22_14_mx0;
  wire [13:0] tile_size_int_sva_6;
  wire [22:0] nl_tile_size_int_sva_6;
  wire [13:0] tile_size_int_sva_7;
  wire [27:0] nl_tile_size_int_sva_7;
  wire [13:0] tile_size_int_sva_8;
  wire [27:0] nl_tile_size_int_sva_8;
  wire [13:0] tile_size_int_sva_9;
  wire [27:0] nl_tile_size_int_sva_9;
  wire [13:0] tile_size_int_sva_10;
  wire [27:0] nl_tile_size_int_sva_10;
  wire tile_size_and_cse;


  // Interconnect Declarations for Component Instantiations 
  wire [69:0] nl_instr_bound_rsci_d;
  assign nl_instr_bound_rsci_d = {instr_bound_rsci_d_69_56 , instr_bound_rsci_d_55_42
      , instr_bound_rsci_d_41_28 , instr_bound_rsci_d_27_14 , instr_bound_rsci_d_13_0};
  wire [69:0] nl_instr_tile_rsci_d;
  assign nl_instr_tile_rsci_d = {reg_tile_size_out_rsci_d_13_9_cse , reg_tile_size_out_rsci_d_8_0_cse
      , instr_tile_rsci_d_55_51 , instr_tile_rsci_d_50_42 , instr_tile_rsci_d_41_37
      , instr_tile_rsci_d_36_28 , instr_tile_rsci_d_27_23 , instr_tile_rsci_d_22_14
      , instr_tile_rsci_d_13_9 , instr_tile_rsci_d_8_0};
  wire [13:0] nl_tile_size_out_rsci_d;
  assign nl_tile_size_out_rsci_d = {reg_tile_size_out_rsci_d_13_9_cse , reg_tile_size_out_rsci_d_8_0_cse};
  ccs_in_v1 #(.rscid(32'sd11),
  .width(32'sd70)) loops_bound_rsci (
      .dat(loops_bound_rsc_dat),
      .idat(loops_bound_rsci_idat)
    );
  ccs_in_v1 #(.rscid(32'sd12),
  .width(32'sd5)) loops_relevancy_rsci (
      .dat(loops_relevancy_rsc_dat),
      .idat(loops_relevancy_rsci_idat)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd14),
  .width(32'sd70)) instr_bound_rsci (
      .d(nl_instr_bound_rsci_d[69:0]),
      .z(instr_bound_rsc_z)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd15),
  .width(32'sd70)) instr_tile_rsci (
      .d(nl_instr_tile_rsci_d[69:0]),
      .z(instr_tile_rsc_z)
    );
  ccs_in_v1 #(.rscid(32'sd126),
  .width(32'sd14)) tile_size_in_rsci (
      .dat(tile_size_in_rsc_dat),
      .idat(tile_size_in_rsci_idat)
    );
  mgc_out_dreg_v2 #(.rscid(32'sd127),
  .width(32'sd14)) tile_size_out_rsci (
      .d(nl_tile_size_out_rsci_d[13:0]),
      .z(tile_size_out_rsc_z)
    );
  ccs_in_v1 #(.rscid(32'sd135),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  assign tile_size_and_cse = ccs_ccore_en & ccs_ccore_start_rsci_idat;
  assign instr_tile_rsci_d_8_0_mx0 = MUX_v_9_2_2((tile_size_in_rsci_idat[8:0]), (tile_size_int_sva_6[8:0]),
      loops_relevancy_rsci_idat[0]);
  assign instr_tile_rsci_d_55_51_mx0 = MUX_v_5_2_2(instr_tile_rsci_d_41_37_mx0, (tile_size_int_sva_9[13:9]),
      loops_relevancy_rsci_idat[3]);
  assign instr_tile_rsci_d_50_42_mx0 = MUX_v_9_2_2(instr_tile_rsci_d_36_28_mx0, (tile_size_int_sva_9[8:0]),
      loops_relevancy_rsci_idat[3]);
  assign tile_size_int_lpi_1_dfm_13_9_1 = MUX_v_5_2_2(5'b00000, (tile_size_int_sva_6[13:9]),
      (loops_relevancy_rsci_idat[0]));
  assign instr_tile_rsci_d_41_37_mx0 = MUX_v_5_2_2(instr_tile_rsci_d_27_23_mx0, (tile_size_int_sva_8[13:9]),
      loops_relevancy_rsci_idat[2]);
  assign instr_tile_rsci_d_36_28_mx0 = MUX_v_9_2_2(instr_tile_rsci_d_22_14_mx0, (tile_size_int_sva_8[8:0]),
      loops_relevancy_rsci_idat[2]);
  assign instr_tile_rsci_d_27_23_mx0 = MUX_v_5_2_2(tile_size_int_lpi_1_dfm_13_9_1,
      (tile_size_int_sva_7[13:9]), loops_relevancy_rsci_idat[1]);
  assign instr_tile_rsci_d_22_14_mx0 = MUX_v_9_2_2(instr_tile_rsci_d_8_0_mx0, (tile_size_int_sva_7[8:0]),
      loops_relevancy_rsci_idat[1]);
  assign nl_tile_size_int_sva_6 = (tile_size_in_rsci_idat[8:0]) * (loops_bound_rsci_idat[13:0]);
  assign tile_size_int_sva_6 = nl_tile_size_int_sva_6[13:0];
  assign nl_tile_size_int_sva_7 = ({tile_size_int_lpi_1_dfm_13_9_1 , instr_tile_rsci_d_8_0_mx0})
      * (loops_bound_rsci_idat[27:14]);
  assign tile_size_int_sva_7 = nl_tile_size_int_sva_7[13:0];
  assign nl_tile_size_int_sva_8 = ({instr_tile_rsci_d_27_23_mx0 , instr_tile_rsci_d_22_14_mx0})
      * (loops_bound_rsci_idat[41:28]);
  assign tile_size_int_sva_8 = nl_tile_size_int_sva_8[13:0];
  assign nl_tile_size_int_sva_9 = ({instr_tile_rsci_d_41_37_mx0 , instr_tile_rsci_d_36_28_mx0})
      * (loops_bound_rsci_idat[55:42]);
  assign tile_size_int_sva_9 = nl_tile_size_int_sva_9[13:0];
  assign nl_tile_size_int_sva_10 = ({instr_tile_rsci_d_55_51_mx0 , instr_tile_rsci_d_50_42_mx0})
      * (loops_bound_rsci_idat[69:56]);
  assign tile_size_int_sva_10 = nl_tile_size_int_sva_10[13:0];
  always @(posedge ccs_ccore_clk) begin
    if ( ccs_ccore_srst ) begin
      reg_tile_size_out_rsci_d_13_9_cse <= 5'b00000;
      reg_tile_size_out_rsci_d_8_0_cse <= 9'b000000000;
      instr_tile_rsci_d_13_9 <= 5'b00000;
    end
    else if ( tile_size_and_cse ) begin
      reg_tile_size_out_rsci_d_13_9_cse <= MUX_v_5_2_2(instr_tile_rsci_d_55_51_mx0,
          (tile_size_int_sva_10[13:9]), loops_relevancy_rsci_idat[4]);
      reg_tile_size_out_rsci_d_8_0_cse <= MUX_v_9_2_2(instr_tile_rsci_d_50_42_mx0,
          (tile_size_int_sva_10[8:0]), loops_relevancy_rsci_idat[4]);
      instr_tile_rsci_d_13_9 <= tile_size_int_lpi_1_dfm_13_9_1;
    end
  end
  always @(posedge ccs_ccore_clk) begin
    if ( ccs_ccore_srst ) begin
      instr_bound_rsci_d_69_56 <= 14'b00000000000000;
      instr_bound_rsci_d_13_0 <= 14'b00000000000000;
      instr_bound_rsci_d_55_42 <= 14'b00000000000000;
      instr_bound_rsci_d_27_14 <= 14'b00000000000000;
      instr_bound_rsci_d_41_28 <= 14'b00000000000000;
      instr_tile_rsci_d_8_0 <= 9'b000000000;
      instr_tile_rsci_d_55_51 <= 5'b00000;
      instr_tile_rsci_d_50_42 <= 9'b000000000;
      instr_tile_rsci_d_41_37 <= 5'b00000;
      instr_tile_rsci_d_36_28 <= 9'b000000000;
      instr_tile_rsci_d_27_23 <= 5'b00000;
      instr_tile_rsci_d_22_14 <= 9'b000000000;
    end
    else if ( ccs_ccore_en ) begin
      instr_bound_rsci_d_69_56 <= MUX_v_14_2_2((loops_bound_rsci_idat[69:56]), 14'b00000000000001,
          loops_relevancy_rsci_idat[4]);
      instr_bound_rsci_d_13_0 <= MUX_v_14_2_2((loops_bound_rsci_idat[13:0]), 14'b00000000000001,
          loops_relevancy_rsci_idat[0]);
      instr_bound_rsci_d_55_42 <= MUX_v_14_2_2((loops_bound_rsci_idat[55:42]), 14'b00000000000001,
          loops_relevancy_rsci_idat[3]);
      instr_bound_rsci_d_27_14 <= MUX_v_14_2_2((loops_bound_rsci_idat[27:14]), 14'b00000000000001,
          loops_relevancy_rsci_idat[1]);
      instr_bound_rsci_d_41_28 <= MUX_v_14_2_2((loops_bound_rsci_idat[41:28]), 14'b00000000000001,
          loops_relevancy_rsci_idat[2]);
      instr_tile_rsci_d_8_0 <= instr_tile_rsci_d_8_0_mx0;
      instr_tile_rsci_d_55_51 <= instr_tile_rsci_d_55_51_mx0;
      instr_tile_rsci_d_50_42 <= instr_tile_rsci_d_50_42_mx0;
      instr_tile_rsci_d_41_37 <= instr_tile_rsci_d_41_37_mx0;
      instr_tile_rsci_d_36_28 <= instr_tile_rsci_d_36_28_mx0;
      instr_tile_rsci_d_27_23 <= instr_tile_rsci_d_27_23_mx0;
      instr_tile_rsci_d_22_14 <= instr_tile_rsci_d_22_14_mx0;
    end
  end

  function automatic [13:0] MUX_v_14_2_2;
    input [13:0] input_0;
    input [13:0] input_1;
    input [0:0] sel;
    reg [13:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_14_2_2 = result;
  end
  endfunction


  function automatic [4:0] MUX_v_5_2_2;
    input [4:0] input_0;
    input [4:0] input_1;
    input [0:0] sel;
    reg [4:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_5_2_2 = result;
  end
  endfunction


  function automatic [8:0] MUX_v_9_2_2;
    input [8:0] input_0;
    input [8:0] input_1;
    input [0:0] sel;
    reg [8:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_9_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    tiling_unit_5_O_addr_type_L3
// ------------------------------------------------------------------


module tiling_unit_5_O_addr_type_L3 (
  loops_bound_rsc_dat, loops_relevancy_rsc_dat, tile_size_in_rsc_dat, tile_size_out_rsc_z,
      instr_bound_rsc_z, instr_tile_rsc_z, ccs_ccore_start_rsc_dat, ccs_ccore_clk,
      ccs_ccore_srst, ccs_ccore_en
);
  input [69:0] loops_bound_rsc_dat;
  input [4:0] loops_relevancy_rsc_dat;
  input [13:0] tile_size_in_rsc_dat;
  output [13:0] tile_size_out_rsc_z;
  output [69:0] instr_bound_rsc_z;
  output [69:0] instr_tile_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_ccore_clk;
  input ccs_ccore_srst;
  input ccs_ccore_en;



  // Interconnect Declarations for Component Instantiations 
  tiling_unit_5_O_addr_type_L3_run tiling_unit_5_O_addr_type_L3_run_inst (
      .loops_bound_rsc_dat(loops_bound_rsc_dat),
      .loops_relevancy_rsc_dat(loops_relevancy_rsc_dat),
      .tile_size_in_rsc_dat(tile_size_in_rsc_dat),
      .tile_size_out_rsc_z(tile_size_out_rsc_z),
      .instr_bound_rsc_z(instr_bound_rsc_z),
      .instr_tile_rsc_z(instr_tile_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_ccore_clk(ccs_ccore_clk),
      .ccs_ccore_srst(ccs_ccore_srst),
      .ccs_ccore_en(ccs_ccore_en)
    );
endmodule



