flow package require MemGen
flow run /MemGen/MemoryGenerator_BuildLib {
VENDOR           Nangate
RTLTOOL          DesignCompiler
TECHNOLOGY       045nm
LIBRARY          sram_128_216_freepdk45_TT_1p0V_25C_lib
MODULE           sram_128_216_freepdk45
OUTPUT_DIR       /users/students/r0678912/Documents/zigzag/hls/mem_macros/new
FILES {
  { FILENAME /users/students/r0678912/Documents/zigzag/hls/mem_macros/sram_128_216_freepdk45.v               FILETYPE Verilog MODELTYPE generic   PARSE 1 PATHTYPE copy STATICFILE 1 VHDL_LIB_MAPS work }
  { FILENAME /users/students/r0678912/Documents/zigzag/hls/mem_macros/sram_128_216_freepdk45_TT_1p0V_25C.lib FILETYPE Liberty MODELTYPE synthesis PARSE 1 PATHTYPE copy STATICFILE 1 VHDL_LIB_MAPS work }
}
VHDLARRAYPATH    {}
WRITEDELAY       0.1
INITDELAY        1
READDELAY        0.0
VERILOGARRAYPATH {}
INPUTDELAY       0.01
TIMEUNIT         1ns
WIDTH            128.0
AREA             87281.39210000001
RDWRRESOLUTION   UNKNOWN
WRITELATENCY     1
READLATENCY      1
DEPTH            256.0
PARAMETERS {
  { PARAMETER DATA_WIDTH TYPE hdl IGNORE 0 MIN 8 MAX 128 DEFAULT 128 }
  { PARAMETER ADDR_WIDTH TYPE hdl IGNORE 0 MIN 0 MAX 11  DEFAULT 11  }
  { PARAMETER RAM_DEPTH  TYPE hdl IGNORE 1 MIN 0 MAX 512 DEFAULT 256 }
  { PARAMETER DELAY      TYPE hdl IGNORE 1 MIN 0 MAX 12  DEFAULT 3   }
}
PORTS {
  { NAME port_0 MODE ReadWrite }
  { NAME port_1 MODE ReadWrite }
}
PINMAPS {
  { PHYPIN clk0  LOGPIN CLOCK        DIRECTION in  WIDTH 1.0        PHASE 1  DEFAULT {} PORTS port_0 }
  { PHYPIN csb0  LOGPIN CHIP_SELECT  DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {} PORTS {}     }
  { PHYPIN web0  LOGPIN WRITE_ENABLE DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {} PORTS port_0 }
  { PHYPIN addr0 LOGPIN ADDRESS      DIRECTION in  WIDTH ADDR_WIDTH PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN din0  LOGPIN DATA_IN      DIRECTION in  WIDTH DATA_WIDTH PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN dout0 LOGPIN DATA_OUT     DIRECTION out WIDTH DATA_WIDTH PHASE {} DEFAULT {} PORTS port_0 }
  { PHYPIN clk1  LOGPIN CLOCK        DIRECTION in  WIDTH 1.0        PHASE 1  DEFAULT {} PORTS port_1 }
  { PHYPIN csb1  LOGPIN CHIP_SELECT  DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {} PORTS {}     }
  { PHYPIN web1  LOGPIN WRITE_ENABLE DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {} PORTS port_1 }
  { PHYPIN addr1 LOGPIN ADDRESS      DIRECTION in  WIDTH ADDR_WIDTH PHASE {} DEFAULT {} PORTS port_1 }
  { PHYPIN din1  LOGPIN DATA_IN      DIRECTION in  WIDTH DATA_WIDTH PHASE {} DEFAULT {} PORTS port_1 }
  { PHYPIN dout1 LOGPIN DATA_OUT     DIRECTION out WIDTH DATA_WIDTH PHASE {} DEFAULT {} PORTS port_1 }
}

}
